# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "Atomistic Simulation Tutorial"
html_title = "Atomistic Simulation Tutorial"
copyright = (
    "Preferred Computational Chemistry, Inc."
)
author = 'Preferred Computational Chemistry, Inc.'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "nbsphinx",
    "nbsphinx_link"
]

nbsphinx_execute = 'never'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'ja'

root_doc = 'index'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_material'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['../../_static']

html_sidebars = {"**": ["globaltoc.html", "localtoc.html", "searchbox.html"]}

html_logo = "../../_static/images/matlantis_white.png"

html_show_sourcelink = False

html_show_sphinx = False

# material theme options (see theme.conf for more information)
html_theme_options = {
    # "base_url": "",
    "repo_url": "https://github.com/matlantis-pfcc/atomistic-simulation-tutorial",
    "repo_name": "Github",
    # "google_analytics_account": "TBD",
    "html_minify": False,  # Should not turn on because nglviewer widget will be broken by this setting
    "html_prettify": False,
    "css_minify": True,
    "repo_type": "github",
    "globaltoc_depth": 1,
    "color_primary": "blue",
    "color_accent": "blue-grey",
    # "touch_icon": "TBD",
    "theme_color": "#003790",
    "master_doc": False,
    "nav_links": [
        {"href": "index", "internal": True, "title": "Top"},
    ],
    "heroes": {
        "index": "Atomistic simulation hands on tutorial on Matlantis",
    },
    "version_dropdown": False,
    "table_classes": ["plain"],
}

html_css_files = [
    'css/custom.css',
    'https://docs.matlantis.com/assets/css/cookie-consent.css',
]

html_js_files = ['js/external-link.js']

# Avoid to plotly error
# See https://github.com/spatialaudio/nbsphinx/issues/572#issuecomment-853389268
mathjax_path = 'https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
mathjax2_config = {
    'tex2jax': {
        'inlineMath': [['$', '$'], ['\\(', '\\)']],
        'processEscapes': True,
        'ignoreClass': 'document',
        'processClass': 'math|output_area',
    }
}

smartquotes = False
